### PR TITLE
change ping to the correct URL

### PR DESCRIPTION
**Pull request by JakeKaad**

### CODE REVIEW

**Comment by JakeKaad** [comment]
ping is not pointing at the correct url.  It should be `/core/admin/ping` 

Reference: https://cwiki.apache.org/confluence/display/solr/Ping

**Comment by mikellevate** [comment]
+1 for this. Correct ping URI is critical to asserting solr is up and running before any requests are made.

**Comment by mikellevate** [comment]
Should probably also check the status code for the ping response. 
```
def solr_running?
      begin
        solr_ping_uri = URI.parse("#{Sunspot.session.config.solr.url}/admin/ping?wt=json")
        Net::HTTP.get_response(solr_ping_uri).value
        true # Solr Ready
      rescue
        false # Solr Not Ready
      end
    end
```

**Comment by gaffneyc** [comment]
Thanks!

**Pull request merged**
